### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/swagketo#11]
Score: 

-  Big Idea, Sponsor
-  Hosting Plan
-  GitHub license
-  WireFrames or Web Page mock ups
-  Key Workflow or actions within site. See recent Tweet
-  Data and any Data Privacy or Security needed. For instance between Admin and Users of system.
-  TimeLines

[Github Pages](https://avabrooks.github.io/swagketo/)

**Comment by jm1021** [comment]
Project ida LinkDN and made association.   Networking platform to connect with on campus statement.   Kyle Eckman seems like credible sponsor.

Talked about a longer term plan for deployment, with current deployed.  They discussed license as free domain.

Nice wireframes, mimicing LinkeDN.   They are really nice including next level pages and discussed including messaging.  

Had bullets of key featurs with some services.   Very impressive, but may be a little big, but show future thinking.

Had a nice diagram but we could not see details.  But impressive in look.  

Requests for feedback and form.   Also, shared web page behind the scene.
