### ISSUE TITLE
Design layouts with color scheme from sponsor

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/swagketo#16]
- [x] Created color scheme in [SCSS ](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/static/scss/custom.scss)to match with [sponsor requirements](https://avabrooks.github.io/swagketo/masterplan)
- [x] Finalized [homepage](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/index.html) 
  - [x] Welcome message with [headers](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/index.html#L46)
  - [x] Implement [logo ](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/index.html#L39)into nav and homepage
  - [x] Created bootstrap [container ](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/index.html#L51-L77)with 'meet the team' format(just needs to be filled out by team) 
- [x] Worked on [network navigation page](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/userpages/networksnav.html) that can future implement many to many relationship

- [Commits](https://github.com/avabrooks/swagketo/commits?/author=avabrooks)

**Comment by ridhimainukurti** [comment]
- has commits of frontend code that showed evidence of coding for long periods of time 
    - individual grade: **1.8/2**
