### ISSUE TITLE
Design and Layouts: 4.65/5; Grader: Kira Liao

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/swagketo#4]
- [x] Organize templates
  - [x] fragments
  - [x] delete unnecessary templates from repo
- [x] Create design and logo
  - [x] color scheme
  - [x] implement with Bootstrap and sassy 
- [x] Create nav bar
  - [x] decide contents
  - [ ] dropdown?
- [x] AP Daily Videos
  - [x] Take notes on 1 and 2
- [x] Start creating essential templates for site

**Grading:**

- GH Team Page and Individual Work Ticket
  - Project and sponsor [objectives ](https://avabrooks.github.io/avarepository/goals)for week, show clear plan due EOD Monday
  - Work on and produce coding artifacts
    - reorganized [controller](https://github.com/avabrooks/swagketo/blob/master/src/main/java/com/nighthawk/csa/MainController.java)
    - [nav bar](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/fragments/nav.html)
    - [bootstrap](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/fragments/nav.html#L15)/[sassy](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/static/scss/custom.scss)
    - new templates:
      - [posts ](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/frontend/posts.html)page
      - [profile](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/userpages/profile_admin.html)
      - [clubs ](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/userpages/clubs.html)
      - [sign up](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/userpages/signup.html)
      - [login](https://github.com/avabrooks/swagketo/blob/master/src/main/resources/templates/userpages/login.html)
    - [commits](https://github.com/avabrooks/swagketo/commits?/author=avabrooks)
  - Show comments, [runtime](http://swagketo.tk/), and drivers/testers
    - comments can be seen in links to code above
  - Produce [tangibles ](https://github.com/avabrooks/swagketo/issues/4)related to coding plan, show sponsor objective met, and provide coding [reflection](https://avabrooks.github.io/avarepository/goals) for week
  - PBL Coders, you will need to watch 2 Faculty lectures per week off of CB with [notes ](https://avabrooks.github.io/avarepository/videos)on GitHub pages

**Comment by 4disease** [comment]
- [ ] Monday project plan
- [ ] Coding artifacts
- [ ] Comments, runtime, drivers/testers
Tangibles
- [ ] Related tangibles in coding plan
- [ ] Sponsor objective met
- [ ] Reflection
CB
- [ ] CB video notes
