### ISSUE TITLE
Scrum Team GitHub Pages

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/swagketo#9]
https://unblocked00.github.io/swagketo/

**Comment by florayuan18** [comment]
1/1 - The page was organized with all the required content.  The initial requirements and direction of the project are clear, thoroughly described in [this](https://unblocked00.github.io/swagketo/web) page.  Additionally, the [jobs](https://unblocked00.github.io/swagketo/) are also clearly laid out.  The Scrum Board is well organized and color-coded well.
